apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: Infrastructure
  metadata:
    creationTimestamp: "2026-06-17T16:56:16Z"
    generation: 1
    name: cluster
    resourceVersion: "571"
    uid: b33b2f9d-dd29-4c05-8e12-d506d7444f04
  spec:
    cloudConfig:
      key: config
      name: cloud-provider-config
    platformSpec:
      type: GCP
  status:
    apiServerInternalURI: https://api-int.ci-ln-0pbb87b-72292.gcp-2.ci.openshift.org:6443
    apiServerURL: https://api.ci-ln-0pbb87b-72292.gcp-2.ci.openshift.org:6443
    controlPlaneTopology: HighlyAvailable
    cpuPartitioning: None
    etcdDiscoveryDomain: ""
    infrastructureName: ci-ln-0pbb87b-72292-kqgf4
    infrastructureTopology: HighlyAvailable
    platform: GCP
    platformStatus:
      gcp:
        cloudLoadBalancerConfig:
          dnsType: PlatformDefault
        projectID: openshift-gce-devel-ci-2
        region: us-central1
      type: GCP
kind: List
metadata:
  resourceVersion: ""
