apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
  creationTimestamp: "2026-06-18T16:45:51Z"
  generation: 1
  name: cluster
  resourceVersion: "591"
  uid: 5bd60047-c83f-4891-9175-c6eab065e71b
spec:
  cloudConfig:
    key: config
    name: cloud-provider-config
  platformSpec:
    type: GCP
status:
  apiServerInternalURI: https://api-int.ci-ln-gsv92fb-72292.gcp-2.ci.openshift.org:6443
  apiServerURL: https://api.ci-ln-gsv92fb-72292.gcp-2.ci.openshift.org:6443
  controlPlaneTopology: HighlyAvailable
  cpuPartitioning: None
  etcdDiscoveryDomain: ""
  infrastructureName: ci-ln-gsv92fb-72292-gw5gc
  infrastructureTopology: HighlyAvailable
  platform: GCP
  platformStatus:
    gcp:
      cloudLoadBalancerConfig:
        dnsType: PlatformDefault
      projectID: openshift-gce-devel-ci-2
      region: us-central1
    type: GCP
