apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
  creationTimestamp: "2026-06-22T17:25:11Z"
  generation: 1
  name: cluster
  resourceVersion: "580"
  uid: e7ac2dd3-5925-44fa-b93d-fc2461223d6a
spec:
  cloudConfig:
    key: config
    name: cloud-provider-config
  platformSpec:
    type: GCP
status:
  apiServerInternalURI: https://api-int.ci-ln-8np31z2-72292.gcp-2.ci.openshift.org:6443
  apiServerURL: https://api.ci-ln-8np31z2-72292.gcp-2.ci.openshift.org:6443
  controlPlaneTopology: HighlyAvailable
  cpuPartitioning: None
  etcdDiscoveryDomain: ""
  infrastructureName: ci-ln-8np31z2-72292-nzmck
  infrastructureTopology: HighlyAvailable
  platform: GCP
  platformStatus:
    gcp:
      cloudLoadBalancerConfig:
        dnsType: PlatformDefault
      projectID: openshift-gce-devel-ci-2
      region: us-central1
    type: GCP
